### ISSUE TITLE
can't install pm2-webshell

### ISSUE THREAD

**Issue by Yankee-by** [pm2-hive/pm2-webshell#16]
Hello there. I can't install pm2-webshell to my Ubuntu 14 server, node 4.4.3. 
`pm2 install pm2-webshell` returned this:

```
[PM2][Module] Installing module pm2-webshell
[PM2][Module] Processing...
...../home/ubuntu/.pm2
├─┬ pm2-logrotate@1.3.1
│ └── UNMET PEER DEPENDENCY bower@*
└─┬ pm2-webshell@1.24.0
  ├── pmx@0.5.9
  └─┬ tty.js@0.2.15
    └─┬ pty.js@0.3.0
      ├── extend@1.2.1
      └── nan@2.0.5

[PM2][Module][ERROR] Unknown module
```

Can you help me with this?

**Comment by olegdizus** [comment]
Same problem

**Comment by mouafa** [comment]
+1

**Comment by TemaSM** [comment]
+1

**Comment by vvvvvitas** [comment]
+1

**Comment by technorodent** [comment]
+1

**Comment by void-soul** [comment]
+1

**Comment by Ridermansb** [comment]
Everyone .. use react insted comment  :+1: :smile:

**Comment by gimox** [comment]
+1

**Comment by s-a** [comment]
using reactions seems to be too difficult :+1:

**Comment by Unitech** [comment]
Please upgrade to PM2 v2 and tell me if that works better:

```
$ npm install Unitech/pm2#development -g
$ pm2 install pm2-webshell
```

If that does not work please upgrade NPM:

```
$ npm install npm -g
```

**Comment by gimox** [comment]
not work
npm 3.10
node 6.x

```
ake: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
make: Leaving directory `/home/ubuntu/.pm2/node_modules/pty.js/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.13.0-74-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/.pm2/node_modules/pty.js
gyp ERR! node -v v6.1.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "pm2-webshell" "--prefix" "/home/ubuntu/.pm2" "--loglevel=error"
npm ERR! node v6.1.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
[PM2][Module] Module downloaded
module.js:440
    throw err;
    ^

Error: Cannot find module '/home/ubuntu/.pm2/node_modules/pm2-webshell/package.json'
    at Function.Module._resolveFilename (module.js:438:15)
    at Module.cachePathsRequire [as require] (/usr/lib/node_modules/pm2/node_modules/cache-require-paths/index.js:29:25)
    at require (internal/module.js:20:19)
    at startModule (/usr/lib/node_modules/pm2/lib/CLI/Modules/Modularizer.js:32:22)
    at /usr/lib/node_modules/pm2/lib/CLI/Modules/Modularizer.js:144:9
    at /usr/lib/node_modules/pm2/lib/Configuration.js:108:14
    at FSReqWrap.oncomplete (fs.js:117:15)
```

**Comment by Unitech** [comment]
https://github.com/chjj/pty.js/search?q=node-gyp&type=Issues&utf8=%E2%9C%93

**Comment by TemaSM** [comment]
Works perfectly :+1: 

Tested on:
**Ubuntu 14.04** LTS x64
Node.js **v4.4.7** / NPM **3.10.3** / PM2 **2.0.0-rc3** (after update from development branch)

Don't forget to install `build-essential`:
`sudo apt-get install build-essential`
otherwise `node-gyp` won't be able to build native Node.js modules required by `pm2-webshell`

**Comment by sergej-s** [comment]
not working:
node v6.3.1
pm2 1.1.3

**Comment by vmarchaud** [comment]
@sergej-s Did you tried to install node-gyp ?

**Comment by rysinal** [comment]
node v4.4.4
pm2 2.4.6
npm 5.0.3

log:
3014 warn enoent ENOENT: no such file or directory, open '/root/.pm2/package.json'
3015 verbose enoent This is related to npm not being able to find a file.
3016 warn .pm2 No description
3017 warn .pm2 No repository field.
3018 warn .pm2 No README data
3019 warn .pm2 No license field.
3020 verbose stack Error: pty.js@0.3.1 install: `node-gyp rebuild`
3020 verbose stack Exit status 1
3020 verbose stack     at EventEmitter.<anonymous> (/usr/local/nodejs/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
3020 verbose stack     at emitTwo (events.js:87:13)
3020 verbose stack     at EventEmitter.emit (events.js:172:7)
3020 verbose stack     at ChildProcess.<anonymous> (/usr/local/nodejs/lib/node_modules/npm/lib/utils/spawn.js:40:14)
3020 verbose stack     at emitTwo (events.js:87:13)
3020 verbose stack     at ChildProcess.emit (events.js:172:7)
3020 verbose stack     at maybeClose (internal/child_process.js:827:16)
3020 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
3020 verbose stack From previous event:
3020 verbose stack     at runAction (/usr/local/nodejs/lib/node_modules/npm/lib/install/actions.js:71:13)
3020 verbose stack     at actions.(anonymous function).actionP.then.BB.fromNode (/usr/local/nodejs/lib/node_modules/npm/lib/install/actions.js:49:17)
3020 verbose stack     at execAction (/usr/local/nodejs/lib/node_modules/npm/lib/install/actions.js:178:18)
3020 verbose stack     at done (/usr/local/nodejs/lib/node_modules/npm/lib/utils/lifecycle.js:136:5)
3020 verbose stack From previous event:
3020 verbose stack     at runSerial (/usr/local/nodejs/lib/node_modules/npm/lib/install/actions.js:154:6)
3020 verbose stack     at doSerial (/usr/local/nodejs/lib/node_modules/npm/lib/install/actions.js:136:3)
3020 verbose stack     at Array.<anonymous> (/usr/local/nodejs/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
3020 verbose stack     at LOOP (/usr/local/nodejs/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
3020 verbose stack     at /usr/local/nodejs/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
3020 verbose stack     at /usr/local/nodejs/lib/node_modules/npm/lib/install/actions.js:128:5
3020 verbose stack     at processImmediate [as _immediateCallback] (timers.js:383:17)
3021 verbose pkgid pty.js@0.3.1
3022 verbose cwd /root/.pm2
3023 verbose Linux 2.6.32-431.el6.x86_64
3024 verbose argv "/usr/local/nodejs/bin/node" "/usr/local/bin/npm" "install" "pm2-webshell" "--loglevel=error"
3025 verbose node v4.4.4
3026 verbose npm  v5.0.3
3027 error code ELIFECYCLE
3028 error errno 1
3029 error pty.js@0.3.1 install: `node-gyp rebuild`
3029 error Exit status 1
3030 error Failed at the pty.js@0.3.1 install script.
3030 error This is probably not a problem with npm. There is likely additional logging output above.
3031 verbose exit [ 1, true ]

what should I do，thanks

**Comment by vkuehn** [comment]
doesn't work for me either...
looks like from the comments it expects some build environment, which simply doesn't exist on my windows box, which is behind a proxy...however pm2 works at least
