### ISSUE TITLE
Error: Module version mismatch. Expected 47, got 46.

### ISSUE THREAD

**Issue by oleg-deezus** [pm2-hive/pm2-webshell#17]
Hi! I got this error. Reinstalling plugin and pm2 don't solves issue.

```
Error: Module version mismatch. Expected 47, got 46.
     at Error (native)
     at Object.Module._extensions..node (module.js:440:18)
     at Module.load (module.js:357:32)
     at Function.Module._load (module.js:314:12)
     at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
     at Module.require (module.js:367:17)
     at require (internal/module.js:16:19)
     at Object.<anonymous> (/Users/olegdizus/.pm2/node_modules/pty.js/lib/pty.js:9:11)
     at Module._compile (module.js:413:34)
     at Object.Module._extensions..js (module.js:422:10)
```

**Comment by soyuka** [comment]
`npm rebuild` or `npm rebuild -g`
