### ISSUE TITLE
module restart again and again, and is finally shown as "errored" by pm2

### ISSUE THREAD

**Issue by VincentDauliac** [pm2-hive/pm2-webshell#18]
I run node v7.1.0 & npm v3.10.9 on a Debian Jessie server.

in the module error log file there's this error showing up at each module restart :

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/home/sel/.pm2/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Function._load (/home/sel/.npm-global/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/sel/.pm2/node_modules/socket.io/lib/manager.js:16:13)

**Comment by DrJume** [comment]
Are you using Node v7 ?
I think its because of that :bulb: !

Just tried it with v7 and its not working anymore

**Comment by dcyou** [comment]
same as you with Node v8.1.1
