### ISSUE TITLE
Wont Install

### ISSUE THREAD

**Issue by madskunker** [pm2-hive/pm2-webshell#23]
173 verbose stack Error: pty.js@0.3.1 install: `node-gyp rebuild`
173 verbose stack Exit status 1
173 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
173 verbose stack     at emitTwo (events.js:126:13)
173 verbose stack     at EventEmitter.emit (events.js:214:7)
173 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
173 verbose stack     at emitTwo (events.js:126:13)
173 verbose stack     at ChildProcess.emit (events.js:214:7)
173 verbose stack     at maybeClose (internal/child_process.js:925:16)
173 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
174 verbose pkgid pty.js@0.3.1
175 verbose cwd /home/ubuntu
176 verbose Linux 4.4.0-1061-aws
177 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "pm2-webshell" "--loglevel=error" "--prefix" "/home/ubuntu/.pm2/modules/pm2-webshell"
178 verbose node v8.11.3
179 verbose npm  v5.6.0
180 error code ELIFECYCLE
181 error errno 1
182 error pty.js@0.3.1 install: `node-gyp rebuild`
182 error Exit status 1

Suggestions please

**Comment by p-mcgowan** [comment]
pty.js node version mismatch - fails on node v10.13.0 as well [chjj/pty.js#195](https://github.com/chjj/pty.js/issues/195).
Suggested solution there was to downgrade to node 9
