### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by dkebler** [pm2-hive/pm2-webshell#6]
on debian jessie with .12.7 node and 3.30 npm.

The install seems to load in all the dependencies but then fails with this in error log (below).

There is indeed a .pm2 directory made by install of pm2 so not sure why the invalid name .pm2

At this state of install there is pm2-webshell directory in users .npm

Seen this before?  Any suggestions?

```
 1571 verbose stack Error: Invalid name: ".pm2"
1571 verbose stack     at ensureValidName (/usr/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:331:15)
1571 verbose stack     at Object.module.exports.fixNameField (/usr/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:210:5)
1571 verbose stack     at /usr/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:32:38
1571 verbose stack     at Array.forEach (native)
1571 verbose stack     at normalize (/usr/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:31:15)
1571 verbose stack     at thenCheckTop (/usr/lib/node_modules/npm/lib/install/validate-tree.js:58:3)
1571 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
1571 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
1571 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
1571 verbose stack     at thenValidateAllPeerDeps (/usr/lib/node_modules/npm/lib/install/validate-tree.js:46:3)
1572 verbose cwd /opt
1573 error Linux 3.16.0-4-amd64
1574 error argv "node" "/usr/bin/npm" "install" "pm2-webshell" "--prefix" "/root/.pm2"
1575 error node v0.12.7
1576 error npm  v3.3.0
1577 error Invalid name: ".pm2"
1578 error If you need help, you may report this error at:
1578 error     <https://github.com/npm/npm/issues>
```

**Comment by Unitech** [comment]
Please retry `pm2 install pm2-webshell`
