### ISSUE TITLE
install errors 

### ISSUE THREAD

**Issue by HERRKIN** [pm2-hive/pm2-webshell#7]
I am using ubuntu with nvm, there are so many errors it throws I prefered not to copy and paste it. it seems compile errors, finally it says it may be an error of pty.js

**Comment by Clechay** [comment]
Same on Centos 7, Node v4.1.1

**Comment by maheshsundaram** [comment]
Any update on this? I'm unable to install as well. On Ubuntu 14.10 with Node v.4.1.2

**Comment by sarmadsangi** [comment]
same issue on OS X Yosemite (10.10.3) with node v4.1.2.

**Comment by seanwendt** [comment]
same 

```
> pty.js@0.2.6 install /home/supportteam/.pm2/node_modules/pm2-webshell/node_modules/modified-tty.js/node_modules/pty.js
> node-gyp rebuild

..make: Entering directory `/home/supportteam/.pm2/node_modules/pm2-webshell/node_modules/modified-tty.js/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
..In file included from ../node_modules/nan/nan_new.h:190:0,
                 from ../node_modules/nan/nan.h:80,
                 from ../src/unix/pty.cc:16:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::Signature>::return_t NanIntern::Factory<v8::Signature>::New(NanIntern::Factory<v8::Signature>::FTH, int, NanIntern::Factory<v8::Signature>::FTH*)’:
../node_modules/nan/nan_implementation_12_inl.h:181:76: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, NanIntern::Factory<v8::Signature>::FTH&, int&, NanIntern::Factory<v8::Signature>::FTH*&)’
   return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                            ^
../node_modules/nan/nan_implementation_12_inl.h:181:76: note: candidate is:
In file included from /home/supportteam/.node-gyp/4.2.1/include/node/node.h:42:0,
                 from ../node_modules/nan/nan.h:24,
                 from ../src/unix/pty.cc:16:
/home/supportteam/.node-gyp/4.2.1/include/node/v8.h:4675:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/home/supportteam/.node-gyp/4.2.1/include/node/v8.h:4675:27: note:   candidate expects 2 arguments, 4 provided
In file included from ../src/unix/pty.cc:16:0:
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:171:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:166:25: error: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:564:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:564:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:568:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:568:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:575:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:575:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/unix/pty.cc:16:
/home/supportteam/.node-gyp/4.2.1/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/supportteam/.node-gyp/4.2.1/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/supportteam/.node-gyp/4.2.1/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/supportteam/.node-gyp/4.2.1/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/unix/pty.cc:16:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:579:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:586:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
../src/unix/pty.cc: In function ‘void PtyFork(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/unix/pty.cc:185:34: warning: ignoring return value of ‘int chdir(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
       if (strlen(cwd)) chdir(cwd);
                                  ^
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
make: Leaving directory `/home/supportteam/.pm2/node_modules/pm2-webshell/node_modules/modified-tty.js/node_modules/pty.js/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/supportteam/.pm2/node_modules/pm2-webshell/node_modules/modified-tty.js/node_modules/pty.js
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

> ws@0.4.32 install /home/supportteam/.pm2/node_modules/pm2-webshell/node_modules/modified-tty.js/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

..make: Entering directory `/home/supportteam/.pm2/node_modules/pm2-webshell/node_modules/modified-tty.js/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/home/supportteam/.pm2/node_modules/pm2-webshell/node_modules/modified-tty.js/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
.npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "pm2-webshell" "--prefix" "/home/supportteam/.pm2"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/supportteam/npm-debug.log
[PM2][Module][ERROR] Unknown module
```

**Comment by cwonrails** [comment]
Errors over here as well. Node 5 with npm 3.3.12 on Mac:

```
pm2 install pm2-webshell
[PM2][Module] Installing module pm2-webshell
[PM2][Module] Processing...
.....
> pty.js@0.2.6 install /Users/christopherwatson/.pm2/node_modules/pty.js
> node-gyp rebuild

....make: Entering directory '/Users/christopherwatson/.pm2/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
..pty.target.mk:110: recipe for target 'Release/obj.target/pty/src/unix/pty.o' failed
make: Leaving directory '/Users/christopherwatson/.pm2/node_modules/pty.js/build'
[PM2][Module] Module downloaded
module.js:339
    throw err;
    ^

Error: Cannot find module '/Users/christopherwatson/.pm2/node_modules/pm2-webshell/package.json'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at startModule (/usr/local/lib/node_modules/pm2/lib/Modularizer.js:40:22)
    at /usr/local/lib/node_modules/pm2/lib/Modularizer.js:151:9
    at /usr/local/lib/node_modules/pm2/lib/Configuration.js:103:14
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by JNK** [comment]
@cwonrails submitted a pull request with fix - see my answer in issue #9
You can test if it works by installing my version `pm2 install pm2-webshell-jnk`

**Comment by Unitech** [comment]
Fixed thanks to @JNK !

**Comment by cwonrails** [comment]
@JNK Thanks a lot!
